# Generated by Django 3.1 on 2020-09-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0002_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_persistent', models.BooleanField()),
                ('seller_flexible', models.BooleanField()),
                ('seller_closer', models.BooleanField()),
                ('seller_consultative', models.BooleanField()),
                ('seller_detail_oriented', models.BooleanField()),
                ('seller_patient', models.BooleanField()),
                ('seller_relatable', models.BooleanField()),
                ('seller_calculated', models.BooleanField()),
                ('seller_talker', models.BooleanField()),
                ('seller_created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_updated_at', models.DateTimeField(auto_now=True)),
                ('seller_traits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_traits', to='login_reg_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_persistent', models.BooleanField()),
                ('buyer_flexible', models.BooleanField()),
                ('buyer_closer', models.BooleanField()),
                ('buyer_consultative', models.BooleanField()),
                ('buyer_detail_oriented', models.BooleanField()),
                ('buyer_patient', models.BooleanField()),
                ('buyer_relatable', models.BooleanField()),
                ('buyer_calculated', models.BooleanField()),
                ('buyer_talker', models.BooleanField()),
                ('buyer_created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_traits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_traits', to='login_reg_app.user')),
            ],
        ),
    ]
