# Generated by Django 2.2 on 2020-08-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_one', models.BooleanField()),
                ('trait_two', models.BooleanField()),
                ('trait_three', models.BooleanField()),
                ('trait_four', models.BooleanField()),
                ('trait_five', models.BooleanField()),
                ('trait_six', models.BooleanField()),
                ('trait_seven', models.BooleanField()),
                ('trait_eight', models.BooleanField()),
                ('trait_nine', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_traits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='login_reg_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.BooleanField()),
                ('question_two', models.BooleanField()),
                ('question_three', models.BooleanField()),
                ('question_four', models.BooleanField()),
                ('question_five', models.BooleanField()),
                ('user_responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='login_reg_app.User')),
            ],
        ),
    ]
