# Generated by Django 2.2 on 2020-09-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_seller_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyertrait',
            old_name='buyer_relatable',
            new_name='buyer_charismatic',
        ),
        migrations.RenameField(
            model_name='sellertrait',
            old_name='seller_relatable',
            new_name='seller_charismatic',
        ),
    ]
