# Generated by Django 3.1 on 2020-08-31 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SellerTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_one', models.BooleanField()),
                ('trait_two', models.BooleanField()),
                ('trait_three', models.BooleanField()),
                ('trait_four', models.BooleanField()),
                ('trait_five', models.BooleanField()),
                ('trait_six', models.BooleanField()),
                ('trait_seven', models.BooleanField()),
                ('trait_eight', models.BooleanField()),
                ('trait_nine', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_traits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_traits', to='gp_salemate_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='SellerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.BooleanField()),
                ('question_two', models.BooleanField()),
                ('question_three', models.BooleanField()),
                ('question_four', models.BooleanField()),
                ('question_five', models.BooleanField()),
                ('seller_responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_questions', to='gp_salemate_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_one', models.BooleanField()),
                ('trait_two', models.BooleanField()),
                ('trait_three', models.BooleanField()),
                ('trait_four', models.BooleanField()),
                ('trait_five', models.BooleanField()),
                ('trait_six', models.BooleanField()),
                ('trait_seven', models.BooleanField()),
                ('trait_eight', models.BooleanField()),
                ('trait_nine', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_traits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_traits', to='gp_salemate_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.BooleanField()),
                ('question_two', models.BooleanField()),
                ('question_three', models.BooleanField()),
                ('question_four', models.BooleanField()),
                ('question_five', models.BooleanField()),
                ('buyer_responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_questions', to='gp_salemate_app.user')),
            ],
        ),
    ]
